# Navigation overrides for mkdocs-awesome-nav
# This file defines the exact navigation structure used by the site.
- Home: index.md
- Demo: demo/quiz-demo.md
- Year 11:
  - Programming Fundamentals:
    - Overview: Year11/ProgrammingFundamentals.md
    - Module Plan: Year11/ProgrammingFundamentals/ModulePlan.md
    - Chapter 01 - Software development:
      - 1.1 Software development steps: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/index.md
      - 1.1 Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/quiz.md
  - The Object-Oriented Paradigm:
    - Overview: Year11/ObjectOrientedParadigm.md
    - Module Plan: Year11/ObjectOrientedParadigm/ModulePlan.md
  - Programming Mechatronics:
    - Overview: Year11/ProgrammingMechatronics.md
    - Module Plan: Year11/ProgrammingMechatronics/ModulePlan.md
- Year 12:
  - Secure Software Architecture:
    - Overview: Year12/SecureSoftwareArchitecture.md
    - Module Plan: Year12/SecureSoftwareArchitecture/ModulePlan.md
  - Programming for the Web:
    - Overview: Year12/ProgrammingForTheWeb.md
    - Module Plan: Year12/ProgrammingForTheWeb/ModulePlan.md
  - Software Automation:
    - Overview: Year12/SoftwareAutomation.md
    - Module Plan: Year12/SoftwareAutomation/ModulePlan.md
  - Software Engineering Project:
    - Overview: Year12/SoftwareEngineeringProject.md
    - Module Plan: Year12/SoftwareEngineeringProject/ModulePlan.md