site_name: NSW HSC Software Engineering Textbook
docs_dir: docs
nav:
  - Home: index.md
  - Year 11:
      - Programming Fundamentals: Year11/ProgrammingFundamentals.md
      - The Object-Oriented Paradigm: Year11/ObjectOrientedParadigm.md
      - Programming Mechatronics: Year11/ProgrammingMechatronics.md
  - Year 12:
      - Secure Software Architecture: Year12/SecureSoftwareArchitecture.md
      - Programming for the Web: Year12/ProgrammingForTheWeb.md
      - Software Automation: Year12/SoftwareAutomation.md
      - Software Engineering Project: Year12/SoftwareEngineeringProject.md
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - toc.follow

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist

plugins:
- search
- mermaid2

extra_css:
  - assets/diagram-modal.css

extra_javascript:
  - assets/diagram-modal.js

extra:
  generator: false