site_name: NSW HSC Software Engineering Textbook
docs_dir: docs
nav:
  - Home: index.md
  - Year 11:
      - Programming Fundamentals:
          - Course Overview: Year11/ProgrammingFundamentals/index.md
          - 1. Software Development:
              - SDLC Overview: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/index.md
              - Requirements: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/requirements.md
              - Specifications: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/specifications.md
              - Design: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/design.md
              - Development: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/development.md
              - Integration: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/integration.md
              - Testing: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/testing.md
              - Deployment: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/deployment.md
              - Maintenance: Year11/ProgrammingFundamentals/01-SoftwareDevelopment/maintenance.md
          - 2. Collaboration Tools:
              - Overview: Year11/ProgrammingFundamentals/02-CollaborationTools/index.md
              - Version Control: Year11/ProgrammingFundamentals/02-CollaborationTools/version-control.md
              - GitHub Workflow: Year11/ProgrammingFundamentals/02-CollaborationTools/github-workflow.md
              - Code Reviews: Year11/ProgrammingFundamentals/02-CollaborationTools/code-reviews.md
              - Project Management: Year11/ProgrammingFundamentals/02-CollaborationTools/project-management.md
          - 3. Data Types & Structures:
              - Overview: Year11/ProgrammingFundamentals/03-DataTypes/index.md
              - Number Systems: Year11/ProgrammingFundamentals/03-DataTypes/number-systems.md
              - Data Types: Year11/ProgrammingFundamentals/03-DataTypes/data-types.md
              - Data Structures: Year11/ProgrammingFundamentals/03-DataTypes/data-structures.md
              - Data Dictionaries: Year11/ProgrammingFundamentals/03-DataTypes/data-dictionaries.md
          - 4. Algorithm Design:
              - Overview: Year11/ProgrammingFundamentals/04-AlgorithmDesign/index.md
              - Computational Thinking: Year11/ProgrammingFundamentals/04-AlgorithmDesign/computational-thinking.md
              - Pseudocode & Flowcharts: Year11/ProgrammingFundamentals/04-AlgorithmDesign/pseudocode-flowcharts.md
              - Algorithm Analysis: Year11/ProgrammingFundamentals/04-AlgorithmDesign/algorithm-analysis.md
              - Structured Algorithms: Year11/ProgrammingFundamentals/04-AlgorithmDesign/structured-algorithms.md
          - 5. Code Development:
              - Overview: Year11/ProgrammingFundamentals/05-CodeDevelopment/index.md
              - Programming Fundamentals: Year11/ProgrammingFundamentals/05-CodeDevelopment/programming-fundamentals.md
              - Testing & Debugging: Year11/ProgrammingFundamentals/05-CodeDevelopment/testing-debugging.md
              - Code Quality: Year11/ProgrammingFundamentals/05-CodeDevelopment/code-quality.md
              - Project Management: Year11/ProgrammingFundamentals/05-CodeDevelopment/project-management.md
          - 6. Assessment & Practice:
              - Overview: Year11/ProgrammingFundamentals/06-Assessment/index.md
              - Coding Exercises: Year11/ProgrammingFundamentals/06-Assessment/coding-exercises.md
              - Challenge Projects: Year11/ProgrammingFundamentals/06-Assessment/challenge-projects.md
              - Review Questions: Year11/ProgrammingFundamentals/06-Assessment/review-questions.md
      - The Object-Oriented Paradigm: Year11/ObjectOrientedParadigm.md
      - Programming Mechatronics: Year11/ProgrammingMechatronics.md
  - Year 12:
      - Secure Software Architecture: Year12/SecureSoftwareArchitecture.md
      - Programming for the Web: Year12/ProgrammingForTheWeb.md
      - Software Automation: Year12/SoftwareAutomation.md
      - Software Engineering Project: Year12/SoftwareEngineeringProject.md

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.follow


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search
  # - mermaid2:
  #     arguments:
  #       securityLevel: 'loose'

extra_css:
  - assets/diagram-modal.css

extra_javascript:
  - assets/diagram-modal.js

extra:
  generator: false