[project]
name = "ai-textbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"mkdocs",
	"mkdocs-material",
	"pymdown-extensions",
	"mkdocs-kroki-plugin",
	"mkdocs-include-markdown-plugin",
	"mkdocs-macros-plugin",
	"mkdocs-git-revision-date-localized-plugin",
	"mkdocs-awesome-nav",
	"requests>=2.32.4",
]

[project.optional-dependencies]
# Development extras: use `pip install -e .[dev]` to install the following tools
dev = [
	"annotated-types",
	"babel",
	"backrefs",
	"beautifulsoup4",
	"bracex",
	"certifi",
	"charset-normalizer",
	"click",
	"colorama",
	"defusedxml",
	"editorconfig",
	"gitdb",
	"gitpython",
	"hjson",
	"jinja2",
	"jsbeautifier",
	"markdown",
	"markupsafe",
	"mergedeep",
	"mkdocs",
	"mkdocs-awesome-nav",
	"mkdocs-get-deps",
	"mkdocs-git-revision-date-localized-plugin",
	"mkdocs-include-markdown-plugin",
	"mkdocs-kroki-plugin",
	"mkdocs-macros-plugin",
	"mkdocs-material",
	"mkdocs-material-extensions",
	"mkdocs-plantuml",
	"natsort",
	"packaging",
	"paginate",
	"pathspec",
	"platformdirs",
	"pydantic",
	"pydantic-core",
	"pygments",
	"pymarkdown",
	"pymdown-extensions",
	"python-dateutil",
	"pytz",
	"pyyaml",
	"pyyaml-env-tag",
	"requests",
	"result",
	"setuptools",
	"six",
	"smmap",
	"soupsieve",
	"super-collections",
	"termcolor",
	"toolz",
	"typing-extensions",
	"typing-inspection",
	"urllib3",
	"watchdog",
	"wcmatch",
	"wheel",
]
