nav:
  - Home: index.md

  - Demo:
    - Overview: demo/README.md
    - PlantUML demo: demo/plantuml-demo.md
    - PlantUML reference: demo/plantuml-readme.md

  - Year 11:
    - Programming Fundamentals:
      - Overview: Year11/ProgrammingFundamentals/index.md
      - Module plan: Year11/ProgrammingFundamentals/ModulePlan.md
      - Chapter 01 — Software Development:
        - 1.1 Software Development Steps:
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/quiz.md
        - 1.2 Tools and Collaboration (IDE + Git):
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-02-Tools-and-Collaboration/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-02-Tools-and-Collaboration/quiz.md
        - 1.3 Documentation and Code Style:
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-03-Documentation-and-Code-Style/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-03-Documentation-and-Code-Style/quiz.md
        - 1.4 Project Management Models (Waterfall vs Agile):
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-04-Project-Management-Models/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-04-Project-Management-Models/quiz.md
      - Chapter 02 — Designing Algorithms:
        - 2.1 Control Structures (Sequence, Selection, Iteration):
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-01-Control-Structures/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-01-Control-Structures/quiz.md
        - 2.2 I/O and Purpose; Desk and Peer Checking:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-02-IO-and-Purpose-Desk-and-Peer-Checking/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-02-IO-and-Purpose-Desk-and-Peer-Checking/quiz.md
        - 2.3 Pseudocode and Flowcharts:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-03-Pseudocode-and-Flowcharts/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-03-Pseudocode-and-Flowcharts/quiz.md
        - 2.4 Structure Charts; Abstraction and Refinement:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-04-Structure-Charts-Abstraction-and-Refinement/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-04-Structure-Charts-Abstraction-and-Refinement/quiz.md
        - 2.5 Subprograms; Procedures and Functions:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-05-Subprograms-Procedures-and-Functions/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-05-Subprograms-Procedures-and-Functions/quiz.md
        - 2.6 Analysing Written Algorithms (Logic and Structure):
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-06-Analysing-Written-Algorithms/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-06-Analysing-Written-Algorithms/quiz.md
        - 2.7 Brief Paradigms Overview:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-07-Brief-Paradigms-Overview/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-07-Brief-Paradigms-Overview/quiz.md
      - Chapter 03 — Data for Software Engineering:
        - 3.1 Number Systems and Two's Complement:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-01-Number-systems-and-twos-complement/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-01-Number-systems-and-twos-complement/quiz.md
        - 3.2 Standard Data Types:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-02-Standard-Data-Types/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-02-Standard-Data-Types/quiz.md
        - 3.3 Data Dictionaries:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-03-Data-Dictionaries/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-03-Data-Dictionaries/quiz.md
        - 3.4 Data Structures Overview:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-04-Data-Structures-Overview/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-04-Data-Structures-Overview/quiz.md
      - Chapter 04 — Developing Solutions with Code:
        - 4.1 Control Structures in Python:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-01-Control-Structures-in-Python/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-01-Control-Structures-in-Python/quiz.md
        - 4.2 Data Structures in Python:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-02-Data-Structures-in-Python/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-02-Data-Structures-in-Python/quiz.md
        - 4.4 Using Standard Modules:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-04-Using-Standard-Modules/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-04-Using-Standard-Modules/quiz.md
        - 4.5 Debugging Tools and Techniques:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-05-Debugging-Tools-and-Techniques/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-05-Debugging-Tools-and-Techniques/quiz.md
        - 4.6 Designing Suitable Test Data:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-06-Designing-Suitable-Test-Data/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-06-Designing-Suitable-Test-Data/quiz.md
        - 4.7 Common Errors and Exceptions:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-07-Common-Errors-and-Exceptions/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-07-Common-Errors-and-Exceptions/quiz.md
    - Object-Oriented Paradigm:
      - Overview: Year11/ObjectOrientedParadigm/index.md
      - Module plan: Year11/ObjectOrientedParadigm/ModulePlan.md
      - Chapter 05 — OOP foundations:
        - 5.1 Objects and classes:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-01-Objects-and-classes/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-01-Objects-and-classes/quiz.md
        - 5.2 Encapsulation and state:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-02-Encapsulation-and-state/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-02-Encapsulation-and-state/quiz.md
        - 5.3 Abstraction, generalisation, inheritance, polymorphism:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-03-Abstraction-generalisation-inheritance-polymorphism/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-03-Abstraction-generalisation-inheritance-polymorphism/quiz.md
        - 5.4 Comparing procedural and OOP:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-04-Comparing-procedural-and-OOP/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-04-Comparing-procedural-and-OOP/quiz.md
        - 5.5 Modelling with class diagrams, structure charts and DFDs:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-05-Modelling-with-class-diagrams-structure-charts-and-DFDs/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-05-Modelling-with-class-diagrams-structure-charts-and-DFDs/quiz.md
        - 5.6 Design process; task definition and decomposition:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-06-Design-process-task-definition-and-decomposition/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-06-Design-process-task-definition-and-decomposition/quiz.md
        - 5.7 Collaboration practices and version control:
          - Content: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-07-Collaboration-practices-and-version-control/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-05-OOP-foundations/Section-07-Collaboration-practices-and-version-control/quiz.md
      - Chapter 06 — Programming in OOP:
        - 6.1 Building classes and composition:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-01-Building-classes-and-composition/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-01-Building-classes-and-composition/quiz.md
        - 6.2 Control structures within methods:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-02-Control-structures-within-methods/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-02-Control-structures-within-methods/quiz.md
        - 6.3 Designing subroutines and stubs:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-03-Designing-subroutines-and-stubs/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-03-Designing-subroutines-and-stubs/quiz.md
        - 6.4 Code quality and maintainability:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-04-Code-quality-and-maintainability/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-04-Code-quality-and-maintainability/quiz.md
        - 6.5 Testing; unit, subsystem, system and quality assurance:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-05-Testing-unit-subsystem-system-and-quality-assurance/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-05-Testing-unit-subsystem-system-and-quality-assurance/quiz.md
        - 6.6 Test strategies; black/white/grey box:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-06-Test-strategies-black-white-grey-box/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-06-Test-strategies-black-white-grey-box/quiz.md
        - 6.7 Code optimisation and assessing effectiveness:
          - Content: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-07-Code-optimisation-and-assessing-effectiveness/index.md
          - Quiz: Year11/ObjectOrientedParadigm/Chapter-06-Programming-in-OOP/Section-07-Code-optimisation-and-assessing-effectiveness/quiz.md
    - Programming Mechatronics:
      - Overview: Year11/ProgrammingMechatronics/index.md
      - Module plan: Year11/ProgrammingMechatronics/ModulePlan.md

  - Year 12:
    - Programming For The Web:
      - Overview: Year12/ProgrammingForTheWeb/index.md
      - Module plan: Year12/ProgrammingForTheWeb/ModulePlan.md
      - Chapter 11 — Web foundations and data transmission:
        - 11.1 Explore the applications of web programming:
          - Content: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-01-Explore-the-applications-of-web-programming/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-01-Explore-the-applications-of-web-programming/quiz.md
        - 11.2 How data moves on the internet:
          - Content: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-02-How-data-moves-on-the-internet-packets-IP-DNS-protocols/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-02-How-data-moves-on-the-internet-packets-IP-DNS-protocols/quiz.md
        - 11.3 Web protocols, ports and secure transport concepts:
          - Content: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-03-Web-protocols-ports-and-secure-transport-concepts/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-03-Web-protocols-ports-and-secure-transport-concepts/quiz.md
        - 11.4 Big data and web architectures:
          - Content: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-04-Big-data-and-web-architectures/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-11-Web-foundations-and-data-transmission/Section-04-Big-data-and-web-architectures/quiz.md
      - Chapter 12 — Designing web applications:
        - 12.1 The role of the W3C and web standards:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-01-The-role-of-the-W3C-and-web-standards/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-01-The-role-of-the-W3C-and-web-standards/quiz.md
        - 12.2 Model elements that form a web development system:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-02-Model-elements-that-form-a-web-development-system/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-02-Model-elements-that-form-a-web-development-system/quiz.md
        - 12.3 Influence of the web browser and developer tools:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-03-Influence-of-the-web-browser-and-developer-tools/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-03-Influence-of-the-web-browser-and-developer-tools/quiz.md
        - 12.4 CSS, UI and UX principles:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-04-CSS-UI-and-UX-principles/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-04-CSS-UI-and-UX-principles/quiz.md
        - 12.5 Front-end code libraries and frameworks:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-05-Front-end-code-libraries-and-frameworks/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-05-Front-end-code-libraries-and-frameworks/quiz.md
        - 12.6 Open-source and content management systems:
          - Content: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-06-Open-source-and-content-management-systems/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-12-Designing-web-applications/Section-06-Open-source-and-content-management-systems/quiz.md
      - Chapter 13 — Back-end, databases, and PWAs:
        - 13.1 Server-side Python with a microframework and the back-end request flow:
          - Content: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-01-Server-side-Python-with-a-microframework-and-the-back-end-request-flow/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-01-Server-side-Python-with-a-microframework-and-the-back-end-request-flow/quiz.md
        - 13.2 Databases; SQL, common queries and ORM comparison:
          - Content: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-02-Databases-SQL-common-queries-and-ORM-comparison/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-02-Databases-SQL-common-queries-and-ORM-comparison/quiz.md
        - 13.3 Performance and page-load management:
          - Content: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-03-Performance-and-page-load-management/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-03-Performance-and-page-load-management/quiz.md
        - 13.4 Designing and implementing a PWA:
          - Content: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-04-Designing-and-implementing-a-PWA/index.md
          - Quiz: Year12/ProgrammingForTheWeb/Chapter-13-Back-end-databases-and-PWAs/Section-04-Designing-and-implementing-a-PWA/quiz.md
    - Secure Software Architecture:
      - Overview: Year12/SecureSoftwareArchitecture/index.md
      - Module plan: Year12/SecureSoftwareArchitecture/ModulePlan.md
    - Software Automation:
      - Overview: Year12/SoftwareAutomation/index.md
      - Module plan: Year12/SoftwareAutomation/ModulePlan.md
    - Software Engineering Project:
      - Overview: Year12/SoftwareEngineeringProject/index.md
      - Module plan: Year12/SoftwareEngineeringProject/ModulePlan.md

sort:
  sections: first