nav:
  - Home: index.md

  - Demo:
    - Overview: demo/README.md
    - PlantUML demo: demo/plantuml-demo.md
    - PlantUML reference: demo/plantuml-readme.md
  - Code tabs sync demo: demo/code-tabs-sync-demo.md

  - Year 11:
    - Programming Fundamentals:
      - Overview: Year11/ProgrammingFundamentals/index.md
      - Module plan: Year11/ProgrammingFundamentals/ModulePlan.md
      - Chapter 01 — Software Development:
        - 1.1 Software Development Steps:
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-01-Software-Development-Steps/quiz.md
        - 1.2 Tools and Collaboration (IDE + Git):
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-02-Tools-and-Collaboration/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-02-Tools-and-Collaboration/quiz.md
        - 1.3 Documentation and Code Style:
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-03-Documentation-and-Code-Style/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-03-Documentation-and-Code-Style/quiz.md
        - 1.4 Project Management Models (Waterfall vs Agile):
          - Content: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-04-Project-Management-Models/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-01-Software-Development/Section-04-Project-Management-Models/quiz.md
      - Chapter 02 — Designing Algorithms:
        - 2.1 Control Structures (Sequence, Selection, Iteration):
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-01-Control-Structures/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-01-Control-Structures/quiz.md
        - 2.2 I/O and Purpose; Desk and Peer Checking:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-02-IO-and-Purpose-Desk-and-Peer-Checking/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-02-IO-and-Purpose-Desk-and-Peer-Checking/quiz.md
        - 2.3 Pseudocode and Flowcharts:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-03-Pseudocode-and-Flowcharts/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-03-Pseudocode-and-Flowcharts/quiz.md
        - 2.4 Structure Charts; Abstraction and Refinement:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-04-Structure-Charts-Abstraction-and-Refinement/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-04-Structure-Charts-Abstraction-and-Refinement/quiz.md
        - 2.5 Subprograms; Procedures and Functions:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-05-Subprograms-Procedures-and-Functions/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-05-Subprograms-Procedures-and-Functions/quiz.md
        - 2.6 Analysing Written Algorithms (Logic and Structure):
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-06-Analysing-Written-Algorithms/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-06-Analysing-Written-Algorithms/quiz.md
        - 2.7 Brief Paradigms Overview:
          - Content: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-07-Brief-Paradigms-Overview/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-02-Designing-Algorithms/Section-07-Brief-Paradigms-Overview/quiz.md
      - Chapter 03 — Data for Software Engineering:
        - 3.1 Number Systems and Two's Complement:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-01-Number-systems-and-twos-complement/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-01-Number-systems-and-twos-complement/quiz.md
        - 3.2 Standard Data Types:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-02-Standard-Data-Types/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-02-Standard-Data-Types/quiz.md
        - 3.3 Data Dictionaries:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-03-Data-Dictionaries/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-03-Data-Dictionaries/quiz.md
        - 3.4 Data Structures Overview:
          - Content: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-04-Data-Structures-Overview/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-03-Data-for-software-engineering/Section-04-Data-Structures-Overview/quiz.md
      - Chapter 04 — Developing Solutions with Code:
        - 4.1 Control Structures in Python:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-01-Control-Structures-in-Python/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-01-Control-Structures-in-Python/quiz.md
        - 4.2 Data Structures in Python:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-02-Data-Structures-in-Python/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-02-Data-Structures-in-Python/quiz.md
        - 4.4 Using Standard Modules:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-04-Using-Standard-Modules/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-04-Using-Standard-Modules/quiz.md
        - 4.5 Debugging Tools and Techniques:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-05-Debugging-Tools-and-Techniques/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-05-Debugging-Tools-and-Techniques/quiz.md
        - 4.6 Designing Suitable Test Data:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-06-Designing-Suitable-Test-Data/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-06-Designing-Suitable-Test-Data/quiz.md
        - 4.7 Common Errors and Exceptions:
          - Content: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-07-Common-Errors-and-Exceptions/index.md
          - Quiz: Year11/ProgrammingFundamentals/Chapter-04-Developing-solutions-with-code/Section-07-Common-Errors-and-Exceptions/quiz.md
    - Object-Oriented Paradigm:
      - Overview: Year11/ObjectOrientedParadigm/index.md
      - Module plan: Year11/ObjectOrientedParadigm/ModulePlan.md
    - Programming Mechatronics:
      - Overview: Year11/ProgrammingMechatronics/index.md
      - Module plan: Year11/ProgrammingMechatronics/ModulePlan.md

  - Year 12:
    - Programming For The Web:
      - Overview: Year12/ProgrammingForTheWeb/index.md
      - Module plan: Year12/ProgrammingForTheWeb/ModulePlan.md
    - Secure Software Architecture:
      - Overview: Year12/SecureSoftwareArchitecture/index.md
      - Module plan: Year12/SecureSoftwareArchitecture/ModulePlan.md
    - Software Automation:
      - Overview: Year12/SoftwareAutomation/index.md
      - Module plan: Year12/SoftwareAutomation/ModulePlan.md
    - Software Engineering Project:
      - Overview: Year12/SoftwareEngineeringProject/index.md
      - Module plan: Year12/SoftwareEngineeringProject/ModulePlan.md

sort:
  sections: first