name: Deploy Docs

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:  # Allow manual triggers

# Cancel in-progress runs when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: python:3.13

    services:
      kroki:
        image: yuzutech/kroki
        env:
          KROKI_MERMAID_HOST: mermaid
          KROKI_BPMN_HOST: bpmn
          KROKI_EXCALIDRAW_HOST: excalidraw
        ports:
          - 8000:8000
      mermaid:
        image: yuzutech/kroki-mermaid
      bpmn:
        image: yuzutech/kroki-bpmn
      excalidraw:
        image: yuzutech/kroki-excalidraw

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git-revision-date plugin
          sparse-checkout: |
            docs
            includes
            overrides
            scripts
            kroki_wrapper.py
            pyproject.toml
            mkdocs.yml

      - name: 🔐 Mark repository safe for git
        shell: bash
        run: |
          # Allow git operations inside the runner workspace
          git config --global --add safe.directory "${{ github.workspace }}"
          git config --global --add safe.directory "$(pwd)"
          echo "✅ Git safe directories configured"

      - name: 👤 Configure git user
        shell: bash
        run: |
          git config --global user.email "78714349+Eatham532@users.noreply.github.com"
          git config --global user.name "Eatham532"
          echo "✅ Git user configured as Eatham532"

      - name: 🔧 Setup Python environment
        shell: bash
        run: |
          set -euo pipefail
          python --version
          python -m pip install --upgrade pip setuptools wheel build

      - name: 📦 Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -e . || python -m pip install .

      - name: 🚀 Deploy to GitHub Pages
        env:
          KROKI_SERVER_URL: http://kroki:8000
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v mkdocs >/dev/null 2>&1; then
            echo "❌ ERROR: mkdocs not found on PATH"
            exit 1
          fi
          echo "🚀 Deploying to GitHub Pages..."
          mkdocs gh-deploy --force --clean --remote-name origin
          echo "✅ Deployment complete!"

  notify-indexnow:
    name: 🔔 Notify Search Engines
    runs-on: ubuntu-latest
    needs: deploy  # Only run after deployment succeeds
    if: success()  # Only run if deployment was successful
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to compare with gh-pages branch
          ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow
      
      - name: 🔧 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: 📦 Install requests library
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      
      - name: 🔔 Notify IndexNow of changes
        shell: bash
        env:
          GITHUB_BASE_SHA: ${{ github.event.before }}  # SHA before the push
        run: |
          echo "🔔 Notifying search engines of changed pages..."
          echo "Comparing ${{ github.event.before }} ... ${{ github.sha }}"
          python scripts/indexnow_notify.py
        continue-on-error: true  # Don't fail workflow if IndexNow has issues
