name: Deploy Docs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.13

    services:
      kroki:
        image: yuzutech/kroki
        env:
          KROKI_MERMAID_HOST: mermaid
          KROKI_BPMN_HOST: bpmn
          KROKI_EXCALIDRAW_HOST: excalidraw
        ports:
          - 8000:8000
      mermaid:
        image: yuzutech/kroki-mermaid
      bpmn:
        image: yuzutech/kroki-bpmn
      excalidraw:
        image: yuzutech/kroki-excalidraw

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes

      - name: Mark repository safe for git
        shell: bash
        run: |
          # Fix 'detected dubious ownership' errors when git is invoked in the runner
          git config --global --add safe.directory "${{ github.workspace }}"
          git config --global --list | sed -n '1,200p'

      - name: Install dependencies
        run: pip install -e .

      - name: Deploy MkDocs site
        env:
          KROKI_SERVER_URL: http://kroki:8000
        shell: bash
        run: mkdocs gh-deploy --force
